#!/bin/bash

#   Name this project
PROJECT=

#   What email should we use for job notifications?
EMAIL=

#	Is data paired-end? ("True" or "False")
PE=True

############################################
##########  Reference Genome Info ##########
############################################

####The following variables are needed for: Genome indexing, and Reference Prep

#	What file format is your genome annotation file? (GTF or GFF3)
#	This variable will be used in the 'Genome Index' and 'Reference Prep' steps
ANNOTATION_FORMAT="GFF3"

#   Where is the Genome Annotation file (GFF3 or GTF)?
#   Include the full filepath
#	This variable will be used in the 'Genome Index' and 'Reference Prep' steps
GEN_ANN=""

#   Where is the Genome FASTA file?
#	Include the full filepath
#	This variable will be used in the 'Genome Index' and 'Reference Prep' steps
GEN_FASTA=""

############################################
##########   Quality_Assessment   ##########
############################################

#   What are our QSub settings for Quality_Assessment?
#       Below are the recommended settings
QA_QSUB="mem=1gb,nodes=1:ppn=4,walltime=6:00:00"

#   Where are the directories that store your raw data?
#	Sunflower_RNAseq is designed for use on the raw data as obtained from the GGBC
#	There is a directory for each sample/lane run (containing 2 files if paired-end)
#	Directories are named in the following format:
#	SampleID_PlateWell_LaneNum-ds.letters/numbers
#       Include the full file path to these directories containing your raw data
QA_INPUTDIR=""

#   Where do you want the FastQC results?
QA_OUTPUTDIR=""

#	A place for FASTQC to store temporary files
QA_TEMP=""

############################################
##########    Adapter_Trimming    ##########
############################################

#   What are our QSub settings for Adapter_Trimming?
#   Below are the recommended settings
AT_QSUB="mem=10gb,nodes=1:ppn=4,walltime=450:00:00"

#   Where are the directories?
#   Include the full file path to the raw directories
AT_INPUTDIR=""

#   Where do you want the Trimmed Samples to go?
AT_OUTPUTDIR=""

#	What is our adapter file? Include the full file path.
ADAPTERFILE=""

#   What shared suffix do the forward samples have?
#       Example: _1_sequence.txt.gz
FORWARD_NAMING=R1_001.fastq.gz

#   What shared suffix do the reverse samples have?
#       Example: _2_sequence.txt.gz
#	(Only relevant for paired-end data)
REVERSE_NAMING=R2_001.fastq.gz

#	The maximum mismatch count allowed for the "seed" (small section of adapter),
#	which causes the entire alignment between the read and adapter to be scored.
SEEDMISMATCH=2

#	The minimum alignment score threshold for clipping adapter sequence
#	A palindroma approach is used to check for adapter 'read-through'
#	This strategy is only used in PE data, but a value must still be supplied if SE data
PALINDROMECLIP=30

#	The minimum alignment score threshold for clipping adapter sequence
SIMPLECLIP=10

#	The minimum length of adapter sequence to be removed
#	Only relevant for Paired-end data
MINADAPTERLEN=1

#	Whether to keep the reverse read if adapter read-through has been detected by palindrome mode
#	the default behavior is to entirely drop the reverse read
#	Only relevant for Paired-end data
KEEPREADS=true

#	Low quality bases are removed from the beginning of the sequence.
#	What is the minimum quality value required to keep a base at the beginning?
LEADCUT=3

#	Low quality bases are removed from the end of the sequence.
#	What is the minimum quality value required to keep a base at the end?
TRAILCUT=3

#	Reads below a specified minimum length are removed (dropped after other processing steps)
#	What is the minimum length required of reads to be kept?
MINLENGTH=20

############################################
##########    Genome_Index        ##########
############################################

#####IMPORTANT:
# The variables: 
# "ANNOTATION_FORMAT", "GEN_ANN" and "GEN_FASTA"
# MUST also be supplied (above, under 'reference genome info')

#   What are our QSub settings for Genome_Index?
#   Below are the recommended settings
GI_QSUB="mem=50gb,nodes=1:ppn=4,walltime=450:00:00"

#	Define the number of threads to be used. 
#	This must be set to the number of available cores on the server node
NTHREAD=4

#   Where do you want the files for your genome index?
#	This direcotry has to be created before program will run and needs writing permissions
#	This directory path will also be used in the next read mapping step
#	Include the full filepath
GEN_DIR=""

#   Specify the length of genomic sequence to be used in constructing the splice junctions database.
#   This length should be equal to ReadLength-1, where ReadLength is the length of reads
#	(ex. for 2x100bp paired-end reads, the ideal value is 99)
SPLICE_JUN=74

############################################
##########    Read_Mapping        ##########
############################################

#####IMPORTANT:
# Make sure that the "GEN_DIR" variable is supplied above (under Genome Index)
# This directory will also be used for read mapping

#	What are our QSub settings for Read_Mapping?
#	Below are the recommended settings
RM_QSUB="mem=50gb,nodes=1:ppn=16,walltime=450:00:00"

#   Where are the trimmed files? Include the full file path
#   This may be the same as your output directory defined in adapter trimming (AT_OUTPUTDIR)
RM_INPUTDIR=""

#   Where do you want your output files to go? Include the full file path
RM_OUTPUTDIR=""

#	Define the number of threads to be used. 
#	This must be set to the number of available cores on the server node
RM_NTHREAD=16

#	The type of quantification requested
#	Either "TranscriptomeSAM" -outputs SAM/BAM alignments to transcriptome in a separate file
#	Or "GeneCounts" - read counts per gene
#	Can also put "-" for none
QUANT=TranscriptomeSAM

#	What is the maximum number of mismatches allowed?
#	Alignment will output only if it has no more mismatches than this value
MAX_MIS=10

#	What is the maximum number of loci the read is allowed to map to?
#	All alignments will output only if the read maps to no more than this value
#	If greater than this value, read counted as "mapped to too many loci"
MAX_N=10

#	Do you want unmapped or partially mapped reads to output in separate fasta/fastq files?
#	If not, put "None", if yes, "Fastx"
UNMAP_F=Fastx

#	What is the minimum score needed for alignment?
#	Normalized by read length- (sum of mates' lengths for paired-end reads)
MINSCORE_READL=0.66

#	What is the minimum number of matched bases needed for alignment?
#	Normalized by read length- (sum of mates' lengths for paired-end reads)
MINMATCH_READL=0.66


############################################
##############    Merge_BAM   ##############
############################################

#	What are our QSub settings for Merge_BAM?
#	Below are the recommended settings
MB_QSUB="mem=10gb,nodes=1:ppn=4,walltime=50:00:00"

#   Where are the BAM files? Include the full file path
#   Make sure that all input files are in the same directory
MB_INPUTDIR=""


############################################
###########    Reference_Prep   ############
############################################

#####IMPORTANT:
# The variables: 
# "ANNOTATION_FORMAT", "GEN_ANN" and "GEN_FASTA"
# MUST also be supplied (above, under 'reference genome info')

#	What are our QSub settings for Preparing the Reference?
#	Below are the recommended settings
RP_QSUB="mem=50gb,nodes=1:ppn=4,walltime=450:00:00"

#	What do you want to call the reference that RSEM prepares?
#	RSEM will generate several reference-related files that are prefixed by this name
#	This name should include path information
REF_NAME=

############################################
##########    Transcript_Quant   ###########
############################################

#	What are our QSub settings for Preparing the Reference?
#	Below are the recommended settings
TQ_QSUB="mem=50gb,nodes=1:ppn=4,walltime=450:00:00"


############################################
##########      Dependencies      ##########
############################################

#   This section defines installations to
#   various dependencies for Sunflower_RNAseq
#   With module paths specific to the Georgia Advanced Computing Resource Center (GACRC)

#   Do we have FastQC installed?
module load FastQC/0.11.8-Java-1.8.0_144

#	Do we have Trimmomatic installed?
module load Trimmomatic/0.36-Java-1.8.0_144

#	Do we have STAR installed?
module load STAR/2.6.1c-foss-2016b

#	Do we have RSEM installed?
module load RSEM/1.3.1-foss-2016b

#	Do we have Samtools installed?
module load SAMtools/1.9-foss-2016b

