#!/bin/bash

#   Name this project
PROJECT=

#   What email should we use for job notifications?
EMAIL=

#	Is data paired-end? ("True" or "False")
PE=True

#   Where is the Genome FASTA file?
#	Include the full filepath
GEN_FASTA=""

#   Where is the Genome Annotation file (GFF3 or GTF)?
#   Include the full filepath
GEN_ANN=""

#	Specify a temporary directory
TEMP_DIR=""

############################################
##############    Merge_BAM   ##############
############################################

#	What are our QSub settings for Merge_BAM?
#	Below are the recommended settings
MB_QSUB="mem=10gb,nodes=1:ppn=4,walltime=5:00:00"

#   What is the file name suffix for the files you are merging? 
MB_SUFFIX="Aligned.sortedByCoord.out.bam"

#   Where are the BAM files? Include the full file path
#   Make sure that all input files are in the same directory
MB_INPUTDIR=""

#   Where do you want your merged bam files to go? Include the whole directory
MB_OUTPUTDIR=""

#   You will need a .txt file with a list of ID's for each sample (1 per line)
#	What is this file called? (Include the full directory path)
ID_NAMES=""

############################################
#############   Process_BAM    #############
############################################

PB_QSUB="mem=22gb,nodes=1:ppn=4,walltime=5:00:00"

#   Where are the BAM files to use? Include the full file path
PB_INPUTDIR=""

#   What is the file name suffix for the files you are processing? 
PB_SUFFIX="merged.bam"

#   Where do you want the output bam files to go? Include the full file path
PB_OUTPUTDIR=""

############################################
############   Validate_BAM    #############
############################################

VB_QSUB="mem=22gb,nodes=1:ppn=4,walltime=5:00:00"

#   Where are the BAM files to use? Include the full file path
VB_INPUTDIR=""

#   What is the file name suffix for the files you are processing? 
VB_SUFFIX="processed.bam"

#   Where do you want the output file to go? Include the full file path
VB_OUTPUTDIR=""

############################################
##########   Haplotype_Caller    ###########
############################################

HC_QSUB="mem=250gb,nodes=1:ppn=24,walltime=150:00:00"

#   Which queue are we submitting the job to?
HC_QUEUE=highmem_q

#   Where are the BAM files? Include a text file with the full filepaths for each .bam file
#	If there are multiple biological replicates per genotype, instead of a .bam file
#	each line can be a file list of the replicate .bam files for each genotype
HC_INPUT=""

#   Where do you want the output file to go? Include the full file path
HC_OUTPUTDIR=""

#   List of genic intervals to process
#	format one per line: chr1:100-200
HC_INTERVALS=""

#	What is the sample heterozygosity?
HETEROZYGOSITY=

############################################
#########   Genomics_DB_Import    ##########
############################################

GD_QSUB="mem=250gb,nodes=1:ppn=24,walltime=150:00:00"

#   Which queue are we submitting the job to?
GD_QUEUE=highmem_q

#	Where are the g.vcf files? (Can be a list or a directory)
GD_INPUT=""

#   Where do you want the output database to go? Include the full file path
GD_OUTPUTDIR=""

#   List of genic intervals to process (Intervals will be parallelized)
#	Accepts GATK, Picard-style or .bed format interval lists
GD_INTERVALS=""

#	Are there scaffolds not covered by the list above? If not, put "false"
#	If yes, put the file filepath to a list of scaffold regions
#	Accepts GATK, Picard-style or .bed format interval lists
GD_SCAFFOLDS="false"

############################################
###########   Genotype_GVCFs    ############
############################################

#### IMPORTANT: This handler shares variables with Genomics_DB_Import
####			It also uses the "HETEROZYGOSITY" variable specified in Haplotype_Caller

GV_QSUB="mem=22gb,nodes=1:ppn=8,walltime=24:00:00"

#   Where do you want the VCF files to go? Include the full file path
GV_OUTPUTDIR=""

############################################
############   Combine_VCFs    #############
############################################


CV_QSUB="mem=50gb,nodes=1:ppn=8,walltime=124:00:00"

#	Where are the input vcf files? Include the full filepath
#	This can be either a directory (such as the one specified in GV_OUTPUTDIR)
#	or a .txt file with a list of all VCFs and their filepaths
#	Chromosome parts must be in the correct order in the list,
#		if a directory, will be ordered by sort -V
CV_INPUT=""

#	Where do you want your final filtered VCF file to go? Include the full filepath
CV_OUTPUTDIR=""


############################################
##########      Dependencies      ##########
############################################

#   This section defines installations to
#   various dependencies for Sunflower_RNAseq
#   With module paths specific to the Georgia Advanced Computing Resource Center (GACRC)

#	Do we have Samtools installed?
module load SAMtools/1.9-foss-2016b

module load GATK/4.1.2.0-GCCcore-8.2.0-Java-1.8
GATK_JAR=/usr/local/apps/eb/GATK/4.1.2.0-GCCcore-8.2.0-Java-1.8/gatk

module load picard/2.21.6-Java-1.8.0_144
PICARD_JAR=/usr/local/apps/eb/picard/2.21.6-Java-1.8.0_144/picard.jar

module load VCFtools/0.1.15-foss-2016b-Perl-5.24.1

module load BCFtools/1.9-foss-2016b



